package io.links.security.entity;

public enum Role {
    ADMIN_SUDO, ADMIN,
    ADMIN_SUDO_POOLS, ADMIN_POOL,
    USER, USER_PARTNER,
    DEVELOPER, SECURITY_MANAGER,
    SERVICE_CLIENT, ORDER_MANAGER,
    BUSINESS_NEEDS_ANALYST,
    MANAGER_TRANSACTIONS
}
